Revert C/CXX compiler version to 14 for OSX
After the upgrade to compiler version 15, the Azure pipelines for OSX
are failing due to the following error when compiling `_geoslib.c`:

   src/_geoslib.c:6269:3: error: incompatible pointer to integer
   conversion returning 'void *' from a function with result type
   'int' [-Wint-conversion]
     import_array();
     ^~~~~~~~~~~~~~